stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker build -t docker.sebbo.net/fhws/find-me-a-room .
    - docker push docker.sebbo.net/fhws/find-me-a-room
  only:
    - develop

publish_github:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/fhws-find-a-room-for-me.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/fhws-find-a-room-for-me.git" --tags

deployment:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  environment:
    name: production
    url: https://api.find-a-room-for.me
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker pull docker.sebbo.net/fhws/find-me-a-room
    - docker stop "findaroomforme" || true
    - docker rm "findaroomforme" || true
    - docker create --restart "always" --name="findaroomforme" -p 127.0.0.1:10039:8080 --link mariadb:db -e "URL=https://api.find-a-room-for.me" -e "DB=${PRODUCTION_DB}" -e "FCM_SERVER_KEY=${PRODUCTION_FCM_SERVER_KEY}" -e "RAVEN_DSN=${PRODUCTION_RAVEN_DSN}" docker.sebbo.net/fhws/find-me-a-room
    - docker start findaroomforme
  only:
    - develop
