stages:
  - build
  - deploy

build_image:
  image: docker:git
  services:
  - docker:dind
  stage: build
  tags:
    - matt.sebbo.net
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker pull docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image:latest
    - docker build -t docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image --cache-from docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image:latest .
    - docker push docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image:latest
  only:
    - develop

push_develop:
  image: docker:git
  services:
  - docker:dind
  stage: build
  tags:
    - matt.sebbo.net
    - docker
  script:
    - pwd
    - git clone ${BITBUCKET_URL} bitbucket
    - cd ./bitbucket/
    - git status
    - git checkout ${CI_COMMIT_REF_NAME}
    - git status
    - rm -rf ./backend/
    - mkdir -p ./backend/
    - cd ../
    - mv ./bin ./bitbucket/backend/
    - mv ./helpers ./bitbucket/backend/
    - mv ./migrations ./bitbucket/backend/
    - mv ./models ./bitbucket/backend/
    - mv ./routes ./bitbucket/backend/
    - mv ./.dockerfile ./bitbucket/backend/
    - mv ./.gitignore ./bitbucket/backend/
    - mv ./.gitlab-ci.yml ./bitbucket/backend/
    - mv ./Dockerfile ./bitbucket/backend/
    - mv ./gruntfile.js ./bitbucket/backend/
    - mv ./package.json ./bitbucket/backend/
    - mv ./server.js ./bitbucket/backend/
    - MESSAGE=$(git log -1 --pretty=%B)
    - cd ./bitbucket/
    - git add -A
    - git status
    - git config --global user.email "${COMMITTER_MAIL}"
    - git config --global user.name "${COMMITTER_NAME}"
    - git commit -m "[Backend] ${MESSAGE}"
    - git push
  only:
    - develop

deploy_develop:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker pull docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image
    - docker stop "findaroomforme"
    - docker rm "findaroomforme"
    - docker create --restart "always" --name="findaroomforme" \
        -p 127.0.0.1:10039:8080 \
        --link mariadb:db \
        -e 'URL=https://api.find-a-room-for.me' \
        -e 'DB=mysql://findaroomforme:vtw8hQUcs4m4XpNBR27P@db:3306/findaroomforme_production' \
        -e 'FCM_SERVER_KEY=AAAAPjG5RJg:APA91bEMZMoUFVChFTDFWyJVCCAxA3TUyGEIE-EzRU1gXzE9Y-oUyzYnZr_-jHQHdMpmFINFED16AO6UmQ5rLgYwhV5gz7E0y1P_Rex5KtuiUFaZhXT3OXPN6MtPMOgyySApElzXxB9r' \
        docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image
    - docker start findaroomforme