build_image:
  image: docker:git
  services:
  - docker:dind
  tags:
    - matt.sebbo.net
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker build -t docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image .
    - docker push docker.sebbo.net/sebbo2002/fhws-find-me-a-room-2/image:latest
  only:
    - develop

push_develop:
  image: docker:git
  services:
  - docker:dind
  tags:
    - matt.sebbo.net
    - docker
  script:
    - pwd
    - git clone ${BITBUCKET_URL} bitbucket
    - cd ./bitbucket/
    - git status
    - git checkout ${CI_COMMIT_REF_NAME}
    - git status
    - cd ../
    - mkdir -p ./backend/
    - mv ./bin ./bitbucket/backend/
    - mv ./helpers ./bitbucket/backend/
    - mv ./migrations ./bitbucket/backend/
    - mv ./models ./bitbucket/backend/
    - mv ./routes ./bitbucket/backend/
    - mv ./.dockerfile ./bitbucket/backend/
    - mv ./.gitignore ./bitbucket/backend/
    - mv ./.gitlab-ci.yml ./bitbucket/backend/
    - mv ./Dockerfile ./bitbucket/backend/
    - mv ./gruntfile.js ./bitbucket/backend/
    - mv ./package.json ./bitbucket/backend/
    - mv ./server.js ./bitbucket/backend/
    - MESSAGE=$(git log -1 --pretty=%B)
    - cd ./bitbucket/
    - git status
    - git commit -am "Backend ${CI_COMMIT_SHA} - ${MESSAGE}"
    - git push
  only:
    - develop
  allow_failure: true